apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentinel-vision-monitor
  labels:
    release: prometheus # app label for prometheus operator to pick up
spec:
  selector:
    matchLabels:
      app: sentinel-vision
  endpoints:
  - port: http
    path: /metrics # FastAPI needs prometheus_client middleware to expose this, adding TODO
    interval: 15s
